# surprisingly, I see a difference when built on my ARM Qualcomm laptop, possibly due to a form of cache?
# I end up commenting out the line with error and beyond, and enter a console with the result so far, and try the next instruction there
# interestingly, each RUN command is as is having a new shell 
FROM ubuntu:noble

# #RUN wget https://apt.kitware.com/kitware-archive.sh
# #RUN bash kitware-archive.sh
# instructions: https://apt.kitware.com/

# https://docs.zephyrproject.org/3.7.0/develop/getting_started/index.html#install-dependencies
## install dependencies
### step1
RUN apt-get update
RUN apt-get install -y ca-certificates gpg wget
RUN test -f /usr/share/doc/kitware-archive-keyring/copyright || wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
RUN echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null
RUN apt-get update
RUN apt-get install kitware-archive-keyring

### step2
RUN apt-get install -y git cmake ninja-build gperf
RUN apt-get install -y ccache dfu-util device-tree-compiler wget
RUN apt-get install -y python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file
RUN apt-get install -y make gcc

RUN apt-get install -y gcc-multilib
RUN apt-get install -y g++-multilib
RUN apt-get install -y libsdl2-dev
RUN apt-get install -y libmagic1

## Get Zephyr and install Python dependencies
RUN apt-get install -y python3-venv
WORKDIR /src

### I believe this part is not useful
# # cd ~/zephyrproject
# WORKDIR /src/zephyrproject
# RUN python3 -m venv ./.venv
# # for use of venv in dockerfile: https://www.reddit.com/r/Python/comments/72v16x/comment/dnm1m6p/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
# RUN . .venv/bin/activate && pip install west
# RUN . .venv/bin/activate && west init /src/zephyrproject
# RUN . .venv/bin/activate && west update
# RUN . .venv/bin/activate && west zephyr-export
# RUN . .venv/bin/activate && pip install -r /src/zephyrproject/zephyr/scripts/requirements.txt

## Install the Zephyr SDK
# cd ~
WORKDIR /src
RUN wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.8/zephyr-sdk-0.16.8_linux-x86_64.tar.xz
RUN if (wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.8/sha256.sum | shasum --check --ignore-missing) ; then \
    tar xvf zephyr-sdk-0.16.8_linux-x86_64.tar.xz ; \
    fi

# cd zephyr-sdk-0.16.8
WORKDIR /src/zephyr-sdk-0.16.8
RUN yes | ./setup.sh

## back to ocre build
### 2. Create a Virtual Python Environment (venv)
WORKDIR /src/runtime
RUN python3 -m venv ./.venv
### 3. Install WEST
RUN . .venv/bin/activate && pip install west
### 4. Initialize the workspace
RUN . .venv/bin/activate && west init -m https://github.com/project-ocre/ocre-runtime.git  
### 5. Update West
RUN . .venv/bin/activate && west update
### 6. Install Additional Zephyr (pip) requirements
RUN . .venv/bin/activate && pip install -r zephyr/scripts/requirements.txt
### 7. Build the application
RUN . .venv/bin/activate && west build -b native_sim ./application -d build -- -DMODULE_EXT_ROOT=`pwd`/application

### 8. Run the application
# ENTRYPOINT [ "/src/runtime/build/zephyr/zephyr.exe" ]