FROM ubuntu:noble

# #RUN wget https://apt.kitware.com/kitware-archive.sh
# #RUN bash kitware-archive.sh
# instructions: https://apt.kitware.com/

# https://docs.zephyrproject.org/3.7.0/develop/getting_started/index.html#install-dependencies
## install dependencies
### step1
RUN apt-get update
RUN apt-get install -y ca-certificates gpg wget
RUN test -f /usr/share/doc/kitware-archive-keyring/copyright || wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
RUN echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null
RUN apt-get update
RUN apt-get install kitware-archive-keyring

### step2
RUN apt-get install -y git cmake ninja-build gperf
RUN apt-get install -y ccache dfu-util device-tree-compiler wget
RUN apt-get install -y python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file
RUN apt-get install -y make gcc

RUN apt-get install -y gcc-multilib
RUN apt-get install -y g++-multilib
RUN apt-get install -y libsdl2-dev
RUN apt-get install -y libmagic1

## Get Zephyr and install Python dependencies
RUN apt-get install python3-venv
WORKDIR /src
RUN python3 -m venv /src/zephyrproject/.venv
# cd ~/zephyrproject
WORKDIR /src/zephyrproject
RUN .venv/bin/pip install west
RUN .venv/bin/west init /src/zephyrproject
RUN .venv/bin/west update
RUN .venv/bin/west zephyr-export
RUN .venv/bin/pip install -r /src/zephyrproject/zephyr/scripts/requirements.txt

## Install the Zephyr SDK
# cd ~
WORKDIR /src
RUN wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.8/zephyr-sdk-0.16.8_linux-x86_64.tar.xz
RUN wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.8/sha256.sum | shasum --check --ignore-missing
RUN tar xvf zephyr-sdk-0.16.8_linux-x86_64.tar.xz

# cd zephyr-sdk-0.16.8
WORKDIR /src/zephyr-sdk-0.16.8
RUN ./setup.sh



# ENTRYPOINT [ "echo", "" ]